import React, { useState } from 'react';
import { Save, AlertTriangle, BookOpen, Check, Edit3 } from 'lucide-react';
import { LectureNote } from '../types';
import { api } from '../api/client';

interface NotesEditorProps {
  lectureId: string;
  note: LectureNote;
  onSaved: () => void;
}

export const NotesEditor: React.FC<NotesEditorProps> = ({ lectureId, note, onSaved }) => {
  const [title, setTitle] = useState(note.title);
  const [summary, setSummary] = useState(note.summary);
  const [isSaving, setIsSaving] = useState(false);
  const [savedStatus, setSavedStatus] = useState(false);

  const handleSave = async () => {
    setIsSaving(true);
    try {
      await api.saveNotes(lectureId, {
        title,
        summary,
        key_concepts: note.key_concepts,
        definitions: note.definitions,
        important_facts: note.important_facts,
        uncertainties: note.uncertainties,
        study_questions: note.study_questions,
      });
      setSavedStatus(true);
      setTimeout(() => setSavedStatus(false), 2000);
      onSaved();
    } catch (err) {
      console.error('Error saving notes:', err);
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      {/* Header bar */}
      <div className="flex items-center justify-between bg-slate-900 border border-slate-800 p-4 rounded-2xl shadow-md">
        <div className="flex items-center space-x-2">
          <BookOpen className="w-5 h-5 text-emerald-400" />
          <div>
            <h3 className="text-base font-bold text-white">Lecture Study Notes</h3>
            <span className="text-xs text-slate-400">
              {note.is_custom_edited ? 'User Custom Edited' : 'Generated by Local AI'}
            </span>
          </div>
        </div>

        <button
          onClick={handleSave}
          disabled={isSaving}
          className="flex items-center space-x-1.5 bg-emerald-600 hover:bg-emerald-500 text-white font-semibold text-xs px-4 py-2 rounded-xl shadow-lg shadow-emerald-600/30 transition disabled:opacity-50"
        >
          {savedStatus ? (
            <>
              <Check className="w-4 h-4 text-white" />
              <span>Saved</span>
            </>
          ) : (
            <>
              <Save className="w-4 h-4" />
              <span>{isSaving ? 'Saving...' : 'Save Edits'}</span>
            </>
          )}
        </button>
      </div>

      {/* Uncertainty callout if present */}
      {note.uncertainties && note.uncertainties.length > 0 && (
        <div className="bg-amber-950/30 border border-amber-800/50 rounded-2xl p-4 text-xs space-y-2">
          <div className="flex items-center space-x-2 text-amber-300 font-semibold">
            <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0" />
            <span>AI Uncertainty Detection</span>
          </div>
          <p className="text-slate-300 text-[11px]">
            The AI detected potentially unclear or muffled lecture audio:
          </p>
          <ul className="list-disc pl-5 space-y-1 text-slate-300">
            {note.uncertainties.map((u, i) => (
              <li key={i}>{u}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Title & Summary */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-md space-y-4">
        <div>
          <label className="block text-xs font-semibold text-slate-400 mb-1 uppercase tracking-wider">
            Lecture Title
          </label>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="w-full bg-slate-950 border border-slate-800 rounded-xl px-4 py-2 text-base font-bold text-white focus:outline-none focus:border-emerald-500"
          />
        </div>

        <div>
          <label className="block text-xs font-semibold text-slate-400 mb-1 uppercase tracking-wider">
            Executive Summary
          </label>
          <textarea
            rows={4}
            value={summary}
            onChange={(e) => setSummary(e.target.value)}
            className="w-full bg-slate-950 border border-slate-800 rounded-xl p-4 text-sm text-slate-200 leading-relaxed focus:outline-none focus:border-emerald-500"
          />
        </div>
      </div>

      {/* Main Topics Breakdown */}
      {note.sections && note.sections.length > 0 && (
        <div className="space-y-4">
          <h4 className="text-sm font-bold text-slate-300 uppercase tracking-wider">Main Topics & Explanations</h4>
          {note.sections.map((sec) => (
            <div key={sec.id} className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-3">
              <div className="flex items-center justify-between border-b border-slate-800 pb-2">
                <h5 className="font-bold text-emerald-400 text-sm">{sec.topic_name}</h5>
                {sec.timestamp_start !== undefined && (
                  <span className="text-[11px] font-mono text-slate-400 bg-slate-950 px-2 py-0.5 rounded border border-slate-800">
                    Timestamp: {Math.floor(sec.timestamp_start / 60)}:{(sec.timestamp_start % 60).toString().padStart(2, '0')}
                  </span>
                )}
              </div>
              <p className="text-xs text-slate-200 leading-relaxed whitespace-pre-wrap">{sec.content}</p>
              {sec.examples && (
                <div className="text-xs bg-slate-950/60 p-2.5 rounded-xl border border-slate-800/80 text-slate-300">
                  <span className="font-semibold text-sky-400">Examples: </span>
                  {sec.examples}
                </div>
              )}
              {sec.terminology && (
                <div className="text-xs text-slate-400">
                  <span className="font-semibold text-slate-300">Key Terms: </span>
                  {sec.terminology}
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {/* Key Concepts & Definitions */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-3">
          <h4 className="text-xs font-bold text-sky-400 uppercase tracking-wider">Key Concepts</h4>
          <ul className="space-y-2 text-xs text-slate-200">
            {(note.key_concepts || []).map((kc, i) => (
              <li key={i} className="flex items-start space-x-2">
                <span className="text-emerald-400 font-bold">•</span>
                <span>{kc}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-3">
          <h4 className="text-xs font-bold text-indigo-400 uppercase tracking-wider">Definitions & Terminology</h4>
          <div className="space-y-2.5 text-xs">
            {(note.definitions || []).map((def, i) => (
              <div key={i} className="bg-slate-950/50 p-2.5 rounded-xl border border-slate-800">
                <span className="font-bold text-slate-100">{def.term}: </span>
                <span className="text-slate-300">{def.definition}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Exam Facts & Study Questions */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-3">
          <h4 className="text-xs font-bold text-amber-400 uppercase tracking-wider">Important Exam Facts</h4>
          <ul className="space-y-2 text-xs text-slate-200">
            {(note.important_facts || []).map((fact, i) => (
              <li key={i} className="flex items-start space-x-2">
                <span className="text-amber-400 font-bold">✓</span>
                <span>{fact}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-3">
          <h4 className="text-xs font-bold text-purple-400 uppercase tracking-wider">Self-Test Study Questions</h4>
          <ul className="space-y-2 text-xs text-slate-200">
            {(note.study_questions || []).map((q, i) => (
              <li key={i} className="flex items-start space-x-2">
                <span className="text-purple-400 font-bold">?</span>
                <span>{q}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
};
